include_guard(GLOBAL)

function(rf_sync_load_artifact repository_root artifact_id output_prefix)
    rf_load_artifact("${repository_root}" "${artifact_id}" locked)
    rf_read_bounded_json("${repository_root}/third_party/artifacts.lock.json" artifact_json)
    string(JSON artifact_count LENGTH "${artifact_json}" artifacts)
    set(found FALSE)
    math(EXPR artifact_last "${artifact_count} - 1")
    foreach(index RANGE 0 ${artifact_last})
        string(JSON candidate_id GET "${artifact_json}" artifacts ${index} id)
        if(candidate_id STREQUAL artifact_id)
            if(found)
                rf_bootstrap_fail("RF1400" "duplicate artifact id in sync authority")
            endif()
            set(found TRUE)
            foreach(field IN ITEMS platform role)
                string(JSON value GET "${artifact_json}" artifacts ${index} ${field})
                set(${output_prefix}_${field} "${value}" PARENT_SCOPE)
            endforeach()
            string(JSON required GET "${artifact_json}" artifacts ${index} signature required)
            set(${output_prefix}_signature_required "${required}" PARENT_SCOPE)
            string(JSON verification_count ERROR_VARIABLE verification_error
                LENGTH "${artifact_json}" artifacts ${index} signature verificationArtifactIds)
            set(verification_ids "")
            if(NOT verification_error)
                math(EXPR verification_last "${verification_count} - 1")
                foreach(verification_index RANGE 0 ${verification_last})
                    string(JSON verification_id GET "${artifact_json}" artifacts ${index}
                        signature verificationArtifactIds ${verification_index})
                    list(APPEND verification_ids "${verification_id}")
                endforeach()
            endif()
            set(${output_prefix}_verification_artifact_ids "${verification_ids}" PARENT_SCOPE)
        endif()
    endforeach()
    if(NOT found)
        rf_bootstrap_fail("RF1401" "required sync artifact is missing")
    endif()
    foreach(field IN ITEMS version byteSize sha256 origin archive_root archive_format signature_scheme
                           expected_identity archive_rootless_entry_count archive_rootless_top_directories
                           archive_rootless_top_files)
        set(${output_prefix}_${field} "${locked_${field}}" PARENT_SCOPE)
    endforeach()
endfunction()

function(rf_sync_acquire_artifact repository_root host_id transport artifact_id output_prefix)
    rf_sync_load_artifact("${repository_root}" "${artifact_id}" artifact)
    set(sync_root "${repository_root}/out/sync/${host_id}")
    set(quarantine_root "${sync_root}/quarantine")
    set(prestaged_root "${sync_root}/prestaged")
    file(MAKE_DIRECTORY "${quarantine_root}")
    set(path "${quarantine_root}/artifact-${artifact_sha256}")
    if(NOT EXISTS "${path}")
        set(prestaged "${prestaged_root}/artifact-${artifact_sha256}")
        if(EXISTS "${prestaged}")
            file(COPY_FILE "${prestaged}" "${path}" ONLY_IF_DIFFERENT)
        else()
            rf_download_manually_redirected(
                "${transport}" "${artifact_origin}" "${path}" "${artifact_byteSize}"
                redirect_hops transport_hosts
            )
        endif()
    endif()
    rf_verify_file_identity("${path}" "${artifact_byteSize}" "${artifact_sha256}"
        "quarantined ${artifact_id}")
    foreach(field IN ITEMS version byteSize sha256 origin archive_root archive_format signature_scheme
                           signature_required expected_identity verification_artifact_ids platform role)
        set(${output_prefix}_${field} "${artifact_${field}}" PARENT_SCOPE)
    endforeach()
    set(${output_prefix}_path "${path}" PARENT_SCOPE)
endfunction()

function(rf_sync_require_prepared_verifiers repository_root host_id output_gpg output_gpgv output_cosign output_root)
    set(tools_root "${repository_root}/out/prepared/${host_id}/tools")
    foreach(tool IN ITEMS gnupg cosign)
        if(NOT EXISTS "${tools_root}/${tool}/.rf-prepared.json")
            rf_bootstrap_fail("RF1402" "prepared ${tool} verifier closure is missing")
        endif()
    endforeach()
    if(host_id STREQUAL "windows-x86_64")
        set(gpg "${tools_root}/gnupg/bin/gpg.exe")
        set(gpgv "${tools_root}/gnupg/bin/gpgv.exe")
        set(cosign "${tools_root}/cosign/bin/cosign.exe")
    elseif(host_id STREQUAL "linux-x86_64")
        set(gpg "${tools_root}/gnupg/bin/gpg")
        set(gpgv "${tools_root}/gnupg/bin/gpgv")
        set(cosign "${tools_root}/cosign/bin/cosign")
    else()
        rf_bootstrap_fail("RF1403" "unsupported sync host")
    endif()
    foreach(executable IN ITEMS gpg gpgv cosign)
        if(NOT EXISTS "${${executable}}" OR IS_DIRECTORY "${${executable}}")
            rf_bootstrap_fail("RF1404" "prepared verifier executable is missing")
        endif()
    endforeach()
    set(trusted_root "${tools_root}/cosign/share/trusted_root.json")
    if(NOT EXISTS "${trusted_root}" OR IS_DIRECTORY "${trusted_root}")
        rf_bootstrap_fail("RF1405" "prepared Sigstore trusted root is missing")
    endif()
    set(${output_gpg} "${gpg}" PARENT_SCOPE)
    set(${output_gpgv} "${gpgv}" PARENT_SCOPE)
    set(${output_cosign} "${cosign}" PARENT_SCOPE)
    set(${output_root} "${trusted_root}" PARENT_SCOPE)
endfunction()

function(rf_sync_cache_path repository_root artifact_id output_path output_root output_format)
    rf_sync_load_artifact("${repository_root}" "${artifact_id}" artifact)
    string(SUBSTRING "${artifact_sha256}" 0 2 prefix)
    set(path "${repository_root}/out/cache/objects/${prefix}/${artifact_sha256}")
    rf_verify_file_identity("${path}" "${artifact_byteSize}" "${artifact_sha256}" "CAS ${artifact_id}")
    set(${output_path} "${path}" PARENT_SCOPE)
    set(${output_root} "${artifact_archive_root}" PARENT_SCOPE)
    set(${output_format} "${artifact_archive_format}" PARENT_SCOPE)
endfunction()

function(rf_sync_verify_required_tree_files repository_root artifact_id tree_root)
    rf_read_bounded_json("${repository_root}/third_party/artifacts.lock.json" artifact_json)
    string(JSON artifact_count LENGTH "${artifact_json}" artifacts)
    set(found FALSE)
    math(EXPR artifact_last "${artifact_count} - 1")
    foreach(artifact_index RANGE 0 ${artifact_last})
        string(JSON candidate_id GET "${artifact_json}" artifacts ${artifact_index} id)
        if(NOT candidate_id STREQUAL artifact_id)
            continue()
        endif()
        set(found TRUE)
        string(JSON required_count ERROR_VARIABLE required_error LENGTH
            "${artifact_json}" artifacts ${artifact_index} archive requiredFiles)
        if(required_error OR required_count LESS 1)
            rf_bootstrap_fail("RF1406" "prepared artifact has no required inner-file authority")
        endif()
        math(EXPR required_last "${required_count} - 1")
        foreach(required_index RANGE 0 ${required_last})
            string(JSON relative GET "${artifact_json}" artifacts ${artifact_index} archive requiredFiles ${required_index} path)
            string(JSON bytes GET "${artifact_json}" artifacts ${artifact_index} archive requiredFiles ${required_index} byteSize)
            string(JSON sha256 GET "${artifact_json}" artifacts ${artifact_index} archive requiredFiles ${required_index} sha256)
            string(FIND "${relative}" "\\" backslash_index)
            if(relative MATCHES "(^|/)[.][.]?(/|$)" OR NOT backslash_index EQUAL -1)
                rf_bootstrap_fail("RF1407" "required prepared path is inadmissible")
            endif()
            rf_verify_file_identity("${tree_root}/${relative}" "${bytes}" "${sha256}"
                "prepared ${artifact_id}:${relative}")
        endforeach()
    endforeach()
    if(NOT found)
        rf_bootstrap_fail("RF1408" "prepared artifact authority is absent")
    endif()
endfunction()
