include_guard(GLOBAL)

function(rf_sync_verify_license_closure repository_root)
    set(index_path "${repository_root}/third_party/licenses/index.json")
    rf_read_bounded_json("${index_path}" license_json)
    rf_require_json_members(license_json "license index" "schemaVersion,materials,entries")
    string(JSON schema_version GET "${license_json}" schemaVersion)
    string(JSON material_count LENGTH "${license_json}" materials)
    string(JSON entry_count LENGTH "${license_json}" entries)
    # Eighteen policies since TASK-0009 admitted the Windows container base layer
    # and one MIT policy covering the four pinned first-party GitHub Actions.
    if(NOT schema_version EQUAL 1 OR NOT material_count EQUAL 5 OR NOT entry_count EQUAL 18)
        rf_bootstrap_fail("RF1450" "offline license closure count/version mismatch")
    endif()
    set(material_paths "")
    math(EXPR material_last "${material_count} - 1")
    foreach(index RANGE 0 ${material_last})
        rf_require_json_members(license_json "license material" "path,byteSize,sha256" materials ${index})
        string(JSON relative GET "${license_json}" materials ${index} path)
        string(JSON bytes GET "${license_json}" materials ${index} byteSize)
        string(JSON sha256 GET "${license_json}" materials ${index} sha256)
        string(FIND "${relative}" "\\" backslash_index)
        if(NOT relative MATCHES "^third_party/licenses/[A-Za-z0-9_./-]+$" OR
           relative MATCHES "(^|/)[.][.]?(/|$)" OR NOT backslash_index EQUAL -1)
            rf_bootstrap_fail("RF1451" "offline license material path is inadmissible")
        endif()
        list(FIND material_paths "${relative}" duplicate_material)
        if(NOT duplicate_material EQUAL -1)
            rf_bootstrap_fail("RF1452" "offline license material path is duplicated")
        endif()
        list(APPEND material_paths "${relative}")
        rf_verify_file_identity("${repository_root}/${relative}" "${bytes}" "${sha256}"
            "offline license material")
    endforeach()

    set(license_ids "")
    math(EXPR entry_last "${entry_count} - 1")
    foreach(index RANGE 0 ${entry_last})
        rf_require_json_members(license_json "license entry"
            "id,catalogIds,spdxExpression,materialPath,sectionHeading,redistribution,approval" entries ${index})
        string(JSON id GET "${license_json}" entries ${index} id)
        string(JSON material_path GET "${license_json}" entries ${index} materialPath)
        string(JSON heading GET "${license_json}" entries ${index} sectionHeading)
        list(FIND license_ids "${id}" duplicate_id)
        list(FIND material_paths "${material_path}" material_index)
        if(NOT duplicate_id EQUAL -1 OR material_index EQUAL -1)
            rf_bootstrap_fail("RF1453" "offline license entry identity/material is invalid")
        endif()
        list(APPEND license_ids "${id}")
        file(READ "${repository_root}/${material_path}" material_content LIMIT 1048577)
        string(FIND "${material_content}" "## ${heading}" heading_offset)
        if(heading_offset EQUAL -1)
            rf_bootstrap_fail("RF1454" "offline license material section is absent")
        endif()
    endforeach()

    rf_read_bounded_json("${repository_root}/third_party/artifacts.lock.json" artifact_json)
    string(JSON artifact_count LENGTH "${artifact_json}" artifacts)
    math(EXPR artifact_last "${artifact_count} - 1")
    foreach(index RANGE 0 ${artifact_last})
        string(JSON artifact_id GET "${artifact_json}" artifacts ${index} id)
        string(JSON license_reference GET "${artifact_json}" artifacts ${index} licenseReference)
        list(FIND license_ids "${license_reference}" license_index)
        if(license_index EQUAL -1)
            rf_bootstrap_fail("RF1455" "artifact has no offline license authority: ${artifact_id}")
        endif()
    endforeach()
endfunction()
