include_guard(GLOBAL)

set(RF_LLVM_VERSION "22.1.8")
set(RF_LLVM_TAG "llvmorg-22.1.8")
set(RF_LLVM_COMMIT "ca7933e47d3a3451d81e72ac174dcb5aa28b59d1")
set(RF_LLVM_SIGNER "FFB3368980F3E6BB5737145A316C56D064CACBA5")
set(RF_LLVM_REPOSITORY "https://github.com/llvm/llvm-project")
set(RF_LLVM_WORKFLOW_ID "https://github.com/llvm/llvm-project/.github/workflows/release-binaries.yml@refs/tags/llvmorg-22.1.8")
set(RF_LLVM_OIDC_ISSUER "https://token.actions.githubusercontent.com")

function(rf_decode_ascii_base64 encoded output)
    string(LENGTH "${encoded}" encoded_length)
    math(EXPR remainder "${encoded_length} % 4")
    if(NOT remainder EQUAL 0 OR encoded_length EQUAL 0)
        rf_bootstrap_fail("RF1410" "LLVM provenance payload has invalid base64 length")
    endif()
    set(alphabet "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
    set(decoded "")
    set(offset 0)
    while(offset LESS encoded_length)
        set(values "")
        set(padding 0)
        foreach(delta RANGE 0 3)
            math(EXPR index "${offset} + ${delta}")
            string(SUBSTRING "${encoded}" ${index} 1 character)
            if(character STREQUAL "=")
                math(EXPR padding "${padding} + 1")
                list(APPEND values 0)
            else()
                if(padding GREATER 0)
                    rf_bootstrap_fail("RF1411" "LLVM provenance payload has interior base64 padding")
                endif()
                string(FIND "${alphabet}" "${character}" value)
                if(value EQUAL -1)
                    rf_bootstrap_fail("RF1412" "LLVM provenance payload contains invalid base64")
                endif()
                list(APPEND values ${value})
            endif()
        endforeach()
        math(EXPR final_quartet_offset "${encoded_length} - 4")
        if(padding GREATER 2 OR (padding GREATER 0 AND NOT offset EQUAL final_quartet_offset))
            rf_bootstrap_fail("RF1413" "LLVM provenance payload has invalid base64 padding")
        endif()
        list(GET values 0 a)
        list(GET values 1 b)
        list(GET values 2 c)
        list(GET values 3 d)
        math(EXPR byte_one "(${a} * 4) + (${b} / 16)")
        math(EXPR byte_two "((${b} % 16) * 16) + (${c} / 4)")
        math(EXPR byte_three "((${c} % 4) * 64) + ${d}")
        if(byte_one GREATER 127 OR byte_one EQUAL 0 OR
           (padding LESS 2 AND (byte_two GREATER 127 OR byte_two EQUAL 0)) OR
           (padding EQUAL 0 AND (byte_three GREATER 127 OR byte_three EQUAL 0)))
            rf_bootstrap_fail("RF1414" "LLVM provenance payload is not bounded ASCII JSON")
        endif()
        string(ASCII ${byte_one} character_one)
        string(APPEND decoded "${character_one}")
        if(padding LESS 2)
            string(ASCII ${byte_two} character_two)
            string(APPEND decoded "${character_two}")
        endif()
        if(padding EQUAL 0)
            string(ASCII ${byte_three} character_three)
            string(APPEND decoded "${character_three}")
        endif()
        math(EXPR offset "${offset} + 4")
    endwhile()
    set(${output} "${decoded}" PARENT_SCOPE)
endfunction()

function(rf_verify_llvm_provenance_semantics bundle_path artifact_name artifact_sha256)
    file(SIZE "${bundle_path}" bundle_size)
    if(bundle_size GREATER 262144)
        rf_bootstrap_fail("RF1415" "LLVM provenance bundle exceeds semantic limit")
    endif()
    file(READ "${bundle_path}" bundle LIMIT 262145)
    string(JSON root_type ERROR_VARIABLE root_error TYPE "${bundle}")
    if(root_error OR NOT root_type STREQUAL "OBJECT")
        rf_bootstrap_fail("RF1416" "LLVM provenance bundle is not one JSON object")
    endif()
    string(JSON media_type GET "${bundle}" mediaType)
    string(JSON payload_type GET "${bundle}" dsseEnvelope payloadType)
    string(JSON signature_count LENGTH "${bundle}" dsseEnvelope signatures)
    if(NOT media_type STREQUAL "application/vnd.dev.sigstore.bundle.v0.3+json" OR
       NOT payload_type STREQUAL "application/vnd.in-toto+json" OR NOT signature_count EQUAL 1)
        rf_bootstrap_fail("RF1417" "LLVM provenance envelope contract mismatch")
    endif()
    string(JSON encoded_payload GET "${bundle}" dsseEnvelope payload)
    rf_decode_ascii_base64("${encoded_payload}" payload)
    string(JSON payload_root ERROR_VARIABLE payload_error TYPE "${payload}")
    if(payload_error OR NOT payload_root STREQUAL "OBJECT")
        rf_bootstrap_fail("RF1418" "LLVM provenance statement is invalid")
    endif()
    string(JSON statement_type GET "${payload}" _type)
    string(JSON predicate_type GET "${payload}" predicateType)
    if(NOT statement_type STREQUAL "https://in-toto.io/Statement/v1" OR
       NOT predicate_type STREQUAL "https://slsa.dev/provenance/v1")
        rf_bootstrap_fail("RF1419" "LLVM provenance statement type mismatch")
    endif()
    string(JSON subject_count LENGTH "${payload}" subject)
    set(subject_matches 0)
    math(EXPR subject_last "${subject_count} - 1")
    foreach(index RANGE 0 ${subject_last})
        string(JSON candidate_name GET "${payload}" subject ${index} name)
        string(JSON candidate_digest ERROR_VARIABLE digest_error GET "${payload}" subject ${index} digest sha256)
        if(candidate_name STREQUAL artifact_name AND NOT digest_error AND candidate_digest STREQUAL artifact_sha256)
            math(EXPR subject_matches "${subject_matches} + 1")
        endif()
    endforeach()
    if(NOT subject_matches EQUAL 1)
        rf_bootstrap_fail("RF1420" "LLVM provenance does not bind the exact artifact once")
    endif()
    string(JSON workflow_ref GET "${payload}" predicate buildDefinition externalParameters workflow ref)
    string(JSON workflow_repository GET "${payload}" predicate buildDefinition externalParameters workflow repository)
    string(JSON workflow_path GET "${payload}" predicate buildDefinition externalParameters workflow path)
    string(JSON dependency_count LENGTH "${payload}" predicate buildDefinition resolvedDependencies)
    string(JSON builder_id GET "${payload}" predicate runDetails builder id)
    if(NOT workflow_ref STREQUAL "refs/tags/${RF_LLVM_TAG}" OR
       NOT workflow_repository STREQUAL RF_LLVM_REPOSITORY OR
       NOT workflow_path STREQUAL ".github/workflows/release-tasks.yml" OR
       NOT dependency_count EQUAL 1 OR NOT builder_id STREQUAL RF_LLVM_WORKFLOW_ID)
        rf_bootstrap_fail("RF1421" "LLVM provenance workflow authority mismatch")
    endif()
    string(JSON source_uri GET "${payload}" predicate buildDefinition resolvedDependencies 0 uri)
    string(JSON source_commit GET "${payload}" predicate buildDefinition resolvedDependencies 0 digest gitCommit)
    if(NOT source_uri STREQUAL "git+${RF_LLVM_REPOSITORY}@refs/tags/${RF_LLVM_TAG}" OR
       NOT source_commit STREQUAL RF_LLVM_COMMIT)
        rf_bootstrap_fail("RF1422" "LLVM provenance source revision mismatch")
    endif()
endfunction()

function(rf_prepare_llvm_keyring gpg key_file work_root output_keyring)
    set(home "${work_root}/llvm-gnupg-home")
    set(keyring "${work_root}/llvm-release-keyring.gpg")
    file(REMOVE_RECURSE "${home}")
    file(REMOVE "${keyring}")
    file(MAKE_DIRECTORY "${home}")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env --unset=GNUPGHOME --unset=GPG_AGENT_INFO
            "${gpg}" --batch --no-options --homedir "${home}" --import "${key_file}"
        RESULT_VARIABLE import_result OUTPUT_VARIABLE import_output ERROR_VARIABLE import_error TIMEOUT 30
    )
    string(LENGTH "${import_output}${import_error}" import_bytes)
    if(NOT import_result EQUAL 0 OR import_bytes GREATER 524288)
        rf_bootstrap_fail("RF1423" "LLVM release-key import failed")
    endif()
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env --unset=GNUPGHOME --unset=GPG_AGENT_INFO
            "${gpg}" --batch --no-options --homedir "${home}" --with-colons --fingerprint "${RF_LLVM_SIGNER}"
        RESULT_VARIABLE fingerprint_result OUTPUT_VARIABLE fingerprint_output ERROR_VARIABLE fingerprint_error TIMEOUT 15
    )
    string(REGEX MATCHALL "fpr:::::::::${RF_LLVM_SIGNER}:" fingerprint_matches "${fingerprint_output}")
    list(LENGTH fingerprint_matches fingerprint_count)
    if(NOT fingerprint_result EQUAL 0 OR NOT fingerprint_count EQUAL 1)
        rf_bootstrap_fail("RF1424" "exact LLVM release signing key is absent or ambiguous")
    endif()
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env --unset=GNUPGHOME --unset=GPG_AGENT_INFO
            "${gpg}" --batch --no-options --homedir "${home}" --export "${RF_LLVM_SIGNER}"
        RESULT_VARIABLE export_result OUTPUT_FILE "${keyring}" ERROR_VARIABLE export_error TIMEOUT 15
    )
    if(NOT export_result EQUAL 0 OR NOT EXISTS "${keyring}")
        rf_bootstrap_fail("RF1425" "cannot create isolated LLVM verification keyring")
    endif()
    set(${output_keyring} "${keyring}" PARENT_SCOPE)
endfunction()

function(rf_verify_llvm_openpgp gpg gpgv gpgconf key_file signature_file artifact_file work_root)
    set(home "${work_root}/llvm-gnupg-home")
    rf_prepare_llvm_keyring("${gpg}" "${key_file}" "${work_root}" keyring)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env --unset=GNUPGHOME --unset=GPG_AGENT_INFO
            "${gpgv}" --homedir "${home}" --status-fd=1 --keyring "${keyring}" "${signature_file}" "${artifact_file}"
        RESULT_VARIABLE verify_result OUTPUT_VARIABLE verify_output ERROR_VARIABLE verify_error TIMEOUT 180
    )
    string(LENGTH "${verify_output}${verify_error}" verify_bytes)
    string(REGEX MATCHALL "VALIDSIG ${RF_LLVM_SIGNER} " valid_matches "${verify_output}")
    list(LENGTH valid_matches valid_count)
    if(NOT verify_result EQUAL 0 OR verify_bytes GREATER 524288 OR NOT valid_count EQUAL 1)
        rf_bootstrap_fail("RF1426" "LLVM detached OpenPGP signature verification failed")
    endif()
    rf_shutdown_gnupg_home("${gpgconf}" "${home}")
endfunction()

function(rf_verify_llvm_sigstore cosign trusted_root bundle artifact_sha256)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env
            --unset=HTTP_PROXY --unset=HTTPS_PROXY --unset=ALL_PROXY --unset=NO_PROXY
            --unset=http_proxy --unset=https_proxy --unset=all_proxy --unset=no_proxy
            --unset=SIGSTORE_ROOT_FILE --unset=SIGSTORE_NO_CACHE
            "${cosign}" verify-blob-attestation --bundle "${bundle}" --trusted-root "${trusted_root}"
            --digest "${artifact_sha256}" --digestAlg sha256 --type slsaprovenance1
            --certificate-identity "${RF_LLVM_WORKFLOW_ID}"
            --certificate-oidc-issuer "${RF_LLVM_OIDC_ISSUER}"
        RESULT_VARIABLE verify_result OUTPUT_VARIABLE verify_output ERROR_VARIABLE verify_error TIMEOUT 120
    )
    string(LENGTH "${verify_output}${verify_error}" verify_bytes)
    if(NOT verify_result EQUAL 0 OR verify_bytes GREATER 524288 OR
       NOT "${verify_output}${verify_error}" MATCHES "Verified OK")
        rf_bootstrap_fail("RF1427" "LLVM Sigstore provenance verification failed")
    endif()
endfunction()

function(rf_sync_verify_llvm_closure repository_root host_id transport output_ids output_paths)
    if(host_id STREQUAL "windows-x86_64")
        set(primary_id "tool.llvm.windows_x86_64")
        set(provenance_id "tool.llvm.windows_x86_64_provenance")
        set(signature_id "tool.llvm.windows_x86_64_signature")
        set(artifact_name "clang+llvm-22.1.8-x86_64-pc-windows-msvc.tar.xz")
    elseif(host_id STREQUAL "linux-x86_64")
        set(primary_id "tool.llvm.linux_x86_64")
        set(provenance_id "tool.llvm.linux_x86_64_provenance")
        set(signature_id "tool.llvm.linux_x86_64_signature")
        set(artifact_name "LLVM-22.1.8-Linux-X64.tar.xz")
    else()
        rf_bootstrap_fail("RF1428" "unsupported LLVM sync host")
    endif()
    set(key_id "authority.llvm_release_keys.data")
    foreach(pair IN ITEMS "${primary_id}|primary" "${provenance_id}|provenance" "${signature_id}|signature" "${key_id}|keys")
        string(REPLACE "|" ";" fields "${pair}")
        list(GET fields 0 artifact_id)
        list(GET fields 1 prefix)
        rf_sync_acquire_artifact("${repository_root}" "${host_id}" "${transport}" "${artifact_id}" ${prefix})
    endforeach()
    set(expected_ids "${key_id};authority.sigstore_trusted_root.data;${provenance_id};${signature_id}")
    if(NOT primary_signature_required OR NOT primary_signature_scheme STREQUAL "gpg_sigstore" OR
       NOT primary_verification_artifact_ids STREQUAL expected_ids)
        rf_bootstrap_fail("RF1429" "LLVM composite verification authority differs from the closed contract")
    endif()
    rf_sync_require_prepared_verifiers("${repository_root}" "${host_id}" gpg gpgv gpgconf cosign trusted_root)
    rf_verify_llvm_provenance_semantics("${provenance_path}" "${artifact_name}" "${primary_sha256}")
    rf_verify_llvm_sigstore("${cosign}" "${trusted_root}" "${provenance_path}" "${primary_sha256}")
    rf_verify_llvm_openpgp("${gpg}" "${gpgv}" "${gpgconf}" "${keys_path}" "${signature_path}" "${primary_path}"
        "${repository_root}/out/sync/${host_id}/quarantine")
    set(${output_ids} "${primary_id};${provenance_id};${signature_id};${key_id}" PARENT_SCOPE)
    set(${output_paths} "${primary_path};${provenance_path};${signature_path};${keys_path}" PARENT_SCOPE)
endfunction()
