#pragma once

#include <cstddef>

namespace rawframe::tool::verify {

// Every input this tool reads is generated by something else: a compiler
// runtime, a test binary, or a version-control system. None of them is hostile,
// and all of them can produce a file large enough to exhaust memory by accident.
// A ceiling that fails loudly is the difference between a bad input and a run
// that never returns.

// A coverage export over a repository of this size is a few megabytes. The
// ceiling is generous because the export grows with the tree and a run that
// stops measuring is worse than a run that allocates.
//
// One node ceiling rather than a node ceiling and a per-container ceiling as
// well. A container cannot hold more elements than the document holds nodes, so two
// numbers meant one of them was always the real bound and the other was
// decoration. The export over this repository is about a million nodes, which
// leaves the ceiling seven times the room the tree currently needs.
inline constexpr std::size_t kMaximumJsonBytes = std::size_t{256} * 1024 * 1024;
inline constexpr std::size_t kMaximumJsonDepth = 64;
inline constexpr std::size_t kMaximumJsonNodes = 8'000'000;

inline constexpr std::size_t kMaximumDiffBytes = std::size_t{64} * 1024 * 1024;
inline constexpr std::size_t kMaximumDiffFiles = 20'000;
inline constexpr std::size_t kMaximumChangedLinesPerFile = 500'000;

// The uncovered set is a review artifact, so it has to stay reviewable. A report
// that lists a hundred thousand lines is a percentage with extra steps.
inline constexpr std::size_t kMaximumReportedUncoveredLines = 4'000;

} // namespace rawframe::tool::verify
