include_guard(GLOBAL)

function(rf_validate_archive_listing archive_path expected_root)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E tar tf "${archive_path}"
        RESULT_VARIABLE list_result
        OUTPUT_VARIABLE listing
        ERROR_VARIABLE list_error
        TIMEOUT 120
    )
    if(NOT list_result EQUAL 0)
        rf_bootstrap_fail("RF1260" "cannot list quarantined archive")
    endif()
    string(LENGTH "${listing}" listing_bytes)
    if(listing_bytes GREATER 16777216)
        rf_bootstrap_fail("RF1261" "archive listing exceeds the bootstrap output limit")
    endif()
    string(REPLACE "\r" "" listing "${listing}")
    string(REPLACE "\n" ";" entries "${listing}")
    list(LENGTH entries entry_count)
    if(entry_count GREATER 300000)
        rf_bootstrap_fail("RF1262" "archive entry count exceeds 300000")
    endif()

    set(casefolded_entries "")
    set(seen_roots "")
    foreach(entry IN LISTS entries)
        if(entry STREQUAL "")
            continue()
        endif()
        string(REGEX REPLACE "/$" "" normalized_entry "${entry}")
        string(LENGTH "${normalized_entry}" entry_bytes)
        if(entry_bytes GREATER 1024 OR normalized_entry MATCHES "\\\\" OR normalized_entry MATCHES ":" OR
           normalized_entry MATCHES "^/" OR normalized_entry MATCHES "^[A-Za-z]:" OR normalized_entry MATCHES "^//" OR
           normalized_entry MATCHES "(^|/)\\.\\.?(/|$)")
            rf_bootstrap_fail("RF1263" "archive contains an inadmissible path")
        endif()
        string(REPLACE "/" ";" components "${normalized_entry}")
        list(LENGTH components component_count)
        if(component_count GREATER 32)
            rf_bootstrap_fail("RF1264" "archive path depth exceeds 32")
        endif()
        list(GET components 0 top_level)
        list(FIND expected_root "${top_level}" admitted_root)
        if(admitted_root EQUAL -1)
            rf_bootstrap_fail("RF1265" "archive contains an unexpected top-level root")
        endif()
        list(APPEND seen_roots "${top_level}")
        foreach(component IN LISTS components)
            string(LENGTH "${component}" component_bytes)
            if(component_bytes GREATER 128 OR component STREQUAL "" OR component STREQUAL "." OR component STREQUAL "..")
                rf_bootstrap_fail("RF1266" "archive contains an inadmissible path component")
            endif()
        endforeach()
        string(TOLOWER "${normalized_entry}" folded_entry)
        list(FIND casefolded_entries "${folded_entry}" collision_index)
        if(NOT collision_index EQUAL -1)
            rf_bootstrap_fail("RF1267" "archive contains duplicate or case-colliding paths")
        endif()
        list(APPEND casefolded_entries "${folded_entry}")
    endforeach()
    list(REMOVE_DUPLICATES seen_roots)
    foreach(required_root IN LISTS expected_root)
        list(FIND seen_roots "${required_root}" observed_root)
        if(observed_root EQUAL -1)
            rf_bootstrap_fail("RF1276" "archive omits a required top-level root")
        endif()
    endforeach()
endfunction()

function(rf_extract_quarantine archive_path expected_root destination)
    rf_validate_archive_listing("${archive_path}" "${expected_root}")
    set(temporary "${destination}.incoming")
    file(REMOVE_RECURSE "${temporary}")
    file(MAKE_DIRECTORY "${temporary}")
    file(ARCHIVE_EXTRACT INPUT "${archive_path}" DESTINATION "${temporary}")
    set(extracted_root "${temporary}/${expected_root}")
    if(NOT EXISTS "${extracted_root}" OR NOT IS_DIRECTORY "${extracted_root}")
        file(REMOVE_RECURSE "${temporary}")
        rf_bootstrap_fail("RF1268" "archive extraction did not produce the locked root")
    endif()

    file(REAL_PATH "${temporary}" temporary_real)
    file(GLOB_RECURSE extracted_entries LIST_DIRECTORIES TRUE "${temporary}/*")
    foreach(extracted_entry IN LISTS extracted_entries)
        file(REAL_PATH "${extracted_entry}" extracted_real)
        cmake_path(IS_PREFIX temporary_real "${extracted_real}" NORMALIZE remains_owned)
        if(NOT remains_owned)
            file(REMOVE_RECURSE "${temporary}")
            rf_bootstrap_fail("RF1269" "archive link or reparse point escapes quarantine")
        endif()
    endforeach()

    if(EXISTS "${destination}")
        file(REMOVE_RECURSE "${temporary}")
        rf_bootstrap_fail("RF1270" "quarantine extraction destination already exists")
    endif()
    file(RENAME "${temporary}" "${destination}" RESULT rename_result)
    if(NOT rename_result STREQUAL "0")
        file(REMOVE_RECURSE "${temporary}")
        rf_bootstrap_fail("RF1271" "cannot atomically publish quarantine extraction")
    endif()
endfunction()

function(rf_extract_multi_root_quarantine archive_path expected_roots destination)
    rf_validate_archive_listing("${archive_path}" "${expected_roots}")
    set(temporary "${destination}.incoming")
    file(REMOVE_RECURSE "${temporary}")
    file(MAKE_DIRECTORY "${temporary}")
    file(ARCHIVE_EXTRACT INPUT "${archive_path}" DESTINATION "${temporary}")
    file(REAL_PATH "${temporary}" temporary_real)
    foreach(required_root IN LISTS expected_roots)
        if(NOT EXISTS "${temporary}/${required_root}")
            file(REMOVE_RECURSE "${temporary}")
            rf_bootstrap_fail("RF1277" "multi-root extraction omitted a locked root")
        endif()
    endforeach()
    file(GLOB_RECURSE extracted_entries LIST_DIRECTORIES TRUE "${temporary}/*")
    foreach(extracted_entry IN LISTS extracted_entries)
        file(REAL_PATH "${extracted_entry}" extracted_real)
        cmake_path(IS_PREFIX temporary_real "${extracted_real}" NORMALIZE remains_owned)
        if(NOT remains_owned)
            file(REMOVE_RECURSE "${temporary}")
            rf_bootstrap_fail("RF1278" "multi-root archive link escapes quarantine")
        endif()
    endforeach()
    if(EXISTS "${destination}")
        file(REMOVE_RECURSE "${temporary}")
        rf_bootstrap_fail("RF1310" "multi-root extraction destination already exists")
    endif()
    file(RENAME "${temporary}" "${destination}" RESULT rename_result)
    if(NOT rename_result STREQUAL "0")
        file(REMOVE_RECURSE "${temporary}")
        rf_bootstrap_fail("RF1311" "cannot publish multi-root quarantine extraction")
    endif()
endfunction()

function(rf_validate_rootless_archive_listing archive_path expected_entries expected_top_directories expected_top_files)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E tar tf "${archive_path}"
        RESULT_VARIABLE list_result
        OUTPUT_VARIABLE listing
        ERROR_VARIABLE list_error
        TIMEOUT 120
    )
    if(NOT list_result EQUAL 0)
        rf_bootstrap_fail("RF1314" "cannot list quarantined rootless archive")
    endif()
    string(LENGTH "${listing}" listing_bytes)
    if(listing_bytes GREATER 16777216)
        rf_bootstrap_fail("RF1315" "rootless archive listing exceeds the bootstrap output limit")
    endif()
    string(REPLACE "\r" "" listing "${listing}")
    string(REPLACE "\n" ";" entries "${listing}")
    list(FILTER entries EXCLUDE REGEX "^$")
    list(LENGTH entries entry_count)
    if(entry_count GREATER 300000)
        rf_bootstrap_fail("RF1316" "rootless archive entry count exceeds 300000")
    endif()
    if(NOT entry_count EQUAL expected_entries)
        rf_bootstrap_fail("RF1317" "rootless archive entry count differs from the lock")
    endif()

    set(casefolded_entries "")
    set(top_directories "")
    set(top_files "")
    foreach(entry IN LISTS entries)
        set(is_directory_entry FALSE)
        if(entry MATCHES "/$")
            set(is_directory_entry TRUE)
        endif()
        string(REGEX REPLACE "/$" "" normalized_entry "${entry}")
        string(LENGTH "${normalized_entry}" entry_bytes)
        if(entry_bytes GREATER 1024 OR normalized_entry MATCHES "\\\\" OR normalized_entry MATCHES ":" OR
           normalized_entry MATCHES "^/" OR normalized_entry MATCHES "^[A-Za-z]:" OR normalized_entry MATCHES "^//" OR
           normalized_entry MATCHES "(^|/)\\.\\.?(/|$)")
            rf_bootstrap_fail("RF1263" "archive contains an inadmissible path")
        endif()
        string(REPLACE "/" ";" components "${normalized_entry}")
        list(LENGTH components component_count)
        if(component_count GREATER 32)
            rf_bootstrap_fail("RF1264" "archive path depth exceeds 32")
        endif()
        foreach(component IN LISTS components)
            string(LENGTH "${component}" component_bytes)
            if(component_bytes GREATER 128 OR component STREQUAL "" OR component STREQUAL "." OR component STREQUAL "..")
                rf_bootstrap_fail("RF1266" "archive contains an inadmissible path component")
            endif()
        endforeach()
        string(TOLOWER "${normalized_entry}" folded_entry)
        list(FIND casefolded_entries "${folded_entry}" collision_index)
        if(NOT collision_index EQUAL -1)
            rf_bootstrap_fail("RF1267" "archive contains duplicate or case-colliding paths")
        endif()
        list(APPEND casefolded_entries "${folded_entry}")
        list(GET components 0 top_level)
        string(TOLOWER "${top_level}" folded_top_level)
        if(component_count GREATER 1 OR is_directory_entry)
            list(APPEND top_directories "${folded_top_level}")
        else()
            list(APPEND top_files "${folded_top_level}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES top_directories)
    list(REMOVE_DUPLICATES top_files)
    foreach(top_file IN LISTS top_files)
        list(FIND top_directories "${top_file}" mixed_index)
        if(NOT mixed_index EQUAL -1)
            rf_bootstrap_fail("RF1318" "rootless archive top-level name is both file and directory")
        endif()
    endforeach()
    list(LENGTH top_directories top_directory_count)
    list(LENGTH top_files top_file_count)
    if(NOT top_directory_count EQUAL expected_top_directories OR NOT top_file_count EQUAL expected_top_files)
        rf_bootstrap_fail("RF1319" "rootless archive top-level shape differs from the lock")
    endif()
endfunction()

function(rf_extract_rootless_quarantine archive_path expected_entries expected_top_directories expected_top_files destination)
    rf_validate_rootless_archive_listing(
        "${archive_path}" "${expected_entries}" "${expected_top_directories}" "${expected_top_files}")
    set(temporary "${destination}.incoming")
    file(REMOVE_RECURSE "${temporary}")
    file(MAKE_DIRECTORY "${temporary}")
    file(ARCHIVE_EXTRACT INPUT "${archive_path}" DESTINATION "${temporary}")
    file(REAL_PATH "${temporary}" temporary_real)
    file(GLOB_RECURSE extracted_entries LIST_DIRECTORIES TRUE "${temporary}/*")
    foreach(extracted_entry IN LISTS extracted_entries)
        file(REAL_PATH "${extracted_entry}" extracted_real)
        cmake_path(IS_PREFIX temporary_real "${extracted_real}" NORMALIZE remains_owned)
        if(NOT remains_owned)
            file(REMOVE_RECURSE "${temporary}")
            rf_bootstrap_fail("RF1320" "rootless archive link or reparse point escapes quarantine")
        endif()
    endforeach()
    if(EXISTS "${destination}")
        file(REMOVE_RECURSE "${temporary}")
        rf_bootstrap_fail("RF1321" "rootless extraction destination already exists")
    endif()
    file(RENAME "${temporary}" "${destination}" RESULT rename_result)
    if(NOT rename_result STREQUAL "0")
        file(REMOVE_RECURSE "${temporary}")
        rf_bootstrap_fail("RF1322" "cannot atomically publish rootless quarantine extraction")
    endif()
endfunction()

function(rf_extract_single_file_archive archive_path expected_file expected_bytes expected_sha256 destination output_file)
    rf_validate_archive_listing("${archive_path}" "${expected_file}")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E tar tf "${archive_path}"
        RESULT_VARIABLE list_result OUTPUT_VARIABLE listing ERROR_VARIABLE list_error TIMEOUT 120
    )
    string(REPLACE "\r" "" listing "${listing}")
    string(REPLACE "\n" ";" entries "${listing}")
    list(FILTER entries EXCLUDE REGEX "^$")
    list(LENGTH entries entry_count)
    if(NOT list_result EQUAL 0 OR NOT entry_count EQUAL 1)
        rf_bootstrap_fail("RF1272" "single-file archive contains an unexpected entry set")
    endif()
    list(GET entries 0 only_entry)
    string(REGEX REPLACE "/$" "" only_entry "${only_entry}")
    if(NOT only_entry STREQUAL expected_file)
        rf_bootstrap_fail("RF1273" "single-file archive entry differs from the lock")
    endif()

    set(incoming "${destination}.incoming")
    file(REMOVE_RECURSE "${incoming}")
    file(MAKE_DIRECTORY "${incoming}")
    file(ARCHIVE_EXTRACT INPUT "${archive_path}" DESTINATION "${incoming}")
    rf_verify_file_identity("${incoming}/${expected_file}" "${expected_bytes}" "${expected_sha256}"
        "single-file archive payload")
    if(EXISTS "${destination}")
        file(REMOVE_RECURSE "${incoming}")
        rf_bootstrap_fail("RF1274" "single-file extraction destination already exists")
    endif()
    file(RENAME "${incoming}" "${destination}" RESULT rename_result)
    if(NOT rename_result STREQUAL "0")
        file(REMOVE_RECURSE "${incoming}")
        rf_bootstrap_fail("RF1275" "cannot publish single-file quarantine extraction")
    endif()
    set(${output_file} "${destination}/${expected_file}" PARENT_SCOPE)
endfunction()
