include_guard(GLOBAL)

function(rf_bootstrap_fail code detail)
    message(FATAL_ERROR "${code} ${detail}")
endfunction()

function(rf_reject_duplicate_json_members json_variable source_path)
    set(content "${${json_variable}}")
    string(LENGTH "${content}" content_length)
    set(index 0)
    set(depth 0)

    while(index LESS content_length)
        string(SUBSTRING "${content}" ${index} 1 character)
        if(character STREQUAL "{")
            math(EXPR depth "${depth} + 1")
            set(context_${depth} "object")
            set(keys_${depth} "")
        elseif(character STREQUAL "[")
            math(EXPR depth "${depth} + 1")
            set(context_${depth} "array")
        elseif(character STREQUAL "}" OR character STREQUAL "]")
            if(depth LESS 1)
                rf_bootstrap_fail("RF1210" "unbalanced JSON structure in ${source_path}")
            endif()
            unset(context_${depth})
            unset(keys_${depth})
            math(EXPR depth "${depth} - 1")
        elseif(character STREQUAL "\"")
            set(token "")
            set(has_escape FALSE)
            set(closed FALSE)
            math(EXPR cursor "${index} + 1")
            while(cursor LESS content_length)
                string(SUBSTRING "${content}" ${cursor} 1 string_character)
                if(string_character STREQUAL "\\")
                    set(has_escape TRUE)
                    math(EXPR cursor "${cursor} + 2")
                    continue()
                endif()
                if(string_character STREQUAL "\"")
                    set(closed TRUE)
                    break()
                endif()
                string(APPEND token "${string_character}")
                math(EXPR cursor "${cursor} + 1")
            endwhile()
            if(NOT closed)
                rf_bootstrap_fail("RF1211" "unterminated JSON string in ${source_path}")
            endif()

            math(EXPR lookahead "${cursor} + 1")
            while(lookahead LESS content_length)
                string(SUBSTRING "${content}" ${lookahead} 1 next_character)
                if(next_character STREQUAL " " OR next_character STREQUAL "\t" OR
                   next_character STREQUAL "\r" OR next_character STREQUAL "\n")
                    math(EXPR lookahead "${lookahead} + 1")
                else()
                    break()
                endif()
            endwhile()

            if(lookahead LESS content_length AND next_character STREQUAL ":")
                if(NOT "${context_${depth}}" STREQUAL "object")
                    rf_bootstrap_fail("RF1212" "JSON member outside an object in ${source_path}")
                endif()
                if(has_escape)
                    rf_bootstrap_fail("RF1213" "escaped JSON member names are forbidden in bootstrap locks: ${source_path}")
                endif()
                if(NOT token MATCHES "^[A-Za-z$][A-Za-z0-9]*$")
                    rf_bootstrap_fail("RF1214" "inadmissible JSON member spelling in ${source_path}")
                endif()
                set(keys_variable "keys_${depth}")
                set(object_keys "${${keys_variable}}")
                list(FIND object_keys "${token}" duplicate_index)
                if(NOT duplicate_index EQUAL -1)
                    rf_bootstrap_fail("RF1215" "duplicate JSON member '${token}' in ${source_path}")
                endif()
                list(APPEND object_keys "${token}")
                set(${keys_variable} "${object_keys}")
            endif()
            set(index ${cursor})
        endif()
        math(EXPR index "${index} + 1")
    endwhile()

    if(NOT depth EQUAL 0)
        rf_bootstrap_fail("RF1216" "unbalanced JSON structure in ${source_path}")
    endif()
endfunction()

function(rf_read_bounded_json path output_variable)
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        rf_bootstrap_fail("RF1217" "required bootstrap lock is missing: ${path}")
    endif()
    file(SIZE "${path}" byte_count)
    if(byte_count GREATER 1048576)
        rf_bootstrap_fail("RF1218" "bootstrap lock exceeds 1048576 bytes: ${path}")
    endif()
    file(READ "${path}" prefix LIMIT 3 HEX)
    if(prefix STREQUAL "efbbbf")
        rf_bootstrap_fail("RF1219" "UTF-8 BOM is forbidden: ${path}")
    endif()
    file(READ "${path}" content LIMIT 1048577)
    rf_reject_duplicate_json_members(content "${path}")
    string(JSON root_type ERROR_VARIABLE json_error TYPE "${content}")
    if(json_error OR NOT root_type STREQUAL "OBJECT")
        rf_bootstrap_fail("RF1220" "bootstrap lock must be one valid JSON object: ${path}")
    endif()
    set(${output_variable} "${content}" PARENT_SCOPE)
endfunction()

function(rf_require_json_members json_variable label expected_csv)
    set(path_tokens ${ARGN})
    set(content "${${json_variable}}")
    string(REPLACE "," ";" expected_members "${expected_csv}")
    list(LENGTH expected_members expected_count)
    string(JSON actual_count ERROR_VARIABLE json_error LENGTH "${content}" ${path_tokens})
    if(json_error OR NOT actual_count EQUAL expected_count)
        rf_bootstrap_fail("RF1221" "${label} has an unexpected member count")
    endif()
    if(actual_count GREATER 0)
        math(EXPR last_index "${actual_count} - 1")
        foreach(member_index RANGE 0 ${last_index})
            string(JSON member_name MEMBER "${content}" ${path_tokens} ${member_index})
            list(FIND expected_members "${member_name}" admitted_index)
            if(admitted_index EQUAL -1)
                rf_bootstrap_fail("RF1222" "${label} contains unknown member '${member_name}'")
            endif()
        endforeach()
    endif()
endfunction()

function(rf_shutdown_gnupg_home gpg home)
    # gpg auto-launches per-homedir helper daemons (gpg-agent, scdaemon,
    # keyboxd) that outlive the calling process and keep their executable
    # images locked, which blocks replacement of the tree they run from.
    # Drain the daemons owned by this private homedir before abandoning it;
    # daemons bound to any other homedir are never touched.
    cmake_path(GET gpg PARENT_PATH gpg_directory)
    cmake_path(GET gpg EXTENSION LAST_ONLY gpg_extension)
    set(gpgconf "${gpg_directory}/gpgconf${gpg_extension}")
    if(NOT EXISTS "${gpgconf}")
        rf_bootstrap_fail("RF1324" "cannot drain GnuPG daemons: gpgconf is missing beside gpg")
    endif()
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env --unset=GNUPGHOME --unset=GPG_AGENT_INFO
            "${gpgconf}" --homedir "${home}" --kill all
        RESULT_VARIABLE kill_result OUTPUT_QUIET ERROR_QUIET TIMEOUT 30
    )
    if(NOT kill_result EQUAL 0)
        rf_bootstrap_fail("RF1325" "cannot drain GnuPG daemons for a private verification home")
    endif()
endfunction()

function(rf_verify_file_identity path expected_bytes expected_sha256 label)
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        rf_bootstrap_fail("RF1223" "${label} is missing")
    endif()
    file(SIZE "${path}" actual_bytes)
    if(NOT actual_bytes EQUAL expected_bytes)
        rf_bootstrap_fail("RF1224" "${label} byte length mismatch")
    endif()
    file(SHA256 "${path}" actual_sha256)
    string(TOLOWER "${actual_sha256}" actual_sha256)
    if(NOT actual_sha256 STREQUAL expected_sha256)
        rf_bootstrap_fail("RF1225" "${label} SHA-256 mismatch")
    endif()
endfunction()

function(rf_load_bootstrap_authority repository_root host_id)
    set(toolchain_path "${repository_root}/third_party/toolchain.lock.json")
    set(artifact_path "${repository_root}/third_party/artifacts.lock.json")
    rf_read_bounded_json("${toolchain_path}" toolchain_json)
    rf_read_bounded_json("${artifact_path}" artifact_json)

    rf_require_json_members(toolchain_json "toolchain lock" "\$schema,schemaVersion,lockVersion,bootstrap,managedTools,compilers,installedSdks,vcpkg")
    rf_require_json_members(toolchain_json "toolchain bootstrap" "minimumCMakeVersion,verifierContractVersion,verifierArtifactIds,transportExecutables" bootstrap)
    string(JSON minimum_cmake GET "${toolchain_json}" bootstrap minimumCMakeVersion)
    string(JSON verifier_contract_version GET "${toolchain_json}" bootstrap verifierContractVersion)
    if(NOT verifier_contract_version EQUAL 1)
        rf_bootstrap_fail("RF1234" "unsupported bootstrap verifier contract")
    endif()

    string(JSON transport_count LENGTH "${toolchain_json}" bootstrap transportExecutables)
    if(NOT transport_count EQUAL 2)
        rf_bootstrap_fail("RF1226" "toolchain bootstrap must contain exactly two host transports")
    endif()
    set(transport_found FALSE)
    math(EXPR transport_last "${transport_count} - 1")
    foreach(transport_index RANGE 0 ${transport_last})
        rf_require_json_members(toolchain_json "bootstrap transport" "hostId,absolutePath,version,byteSize,binarySha256,packageIdentity" bootstrap transportExecutables ${transport_index})
        string(JSON candidate_host GET "${toolchain_json}" bootstrap transportExecutables ${transport_index} hostId)
        if(candidate_host STREQUAL host_id)
            if(transport_found)
                rf_bootstrap_fail("RF1227" "duplicate bootstrap transport for ${host_id}")
            endif()
            set(transport_found TRUE)
            foreach(field IN ITEMS absolutePath version byteSize binarySha256 packageIdentity)
                string(JSON transport_${field} GET "${toolchain_json}" bootstrap transportExecutables ${transport_index} ${field})
            endforeach()
        endif()
    endforeach()
    if(NOT transport_found)
        rf_bootstrap_fail("RF1228" "bootstrap transport is missing for ${host_id}")
    endif()

    rf_require_json_members(artifact_json "artifact lock" "\$schema,schemaVersion,lockVersion,artifacts")
    string(JSON artifact_count LENGTH "${artifact_json}" artifacts)
    if(artifact_count LESS 1 OR artifact_count GREATER 4096)
        rf_bootstrap_fail("RF1229" "artifact lock count is outside bootstrap limits")
    endif()
    string(REPLACE "-" "_" host_token "${host_id}")
    set(expected_artifact_id "tool.cmake.${host_token}")
    set(artifact_found FALSE)
    math(EXPR artifact_last "${artifact_count} - 1")
    foreach(artifact_index RANGE 0 ${artifact_last})
        rf_require_json_members(artifact_json "artifact entry" "id,catalogId,version,platform,architectures,role,origins,byteSize,sha256,signature,archive,licenseReference,reviewReference" artifacts ${artifact_index})
        string(JSON candidate_id GET "${artifact_json}" artifacts ${artifact_index} id)
        if(candidate_id STREQUAL expected_artifact_id)
            if(artifact_found)
                rf_bootstrap_fail("RF1230" "duplicate bootstrap CMake artifact")
            endif()
            set(artifact_found TRUE)
            foreach(field IN ITEMS version byteSize sha256 role)
                string(JSON cmake_${field} GET "${artifact_json}" artifacts ${artifact_index} ${field})
            endforeach()
            string(JSON origin_count LENGTH "${artifact_json}" artifacts ${artifact_index} origins)
            if(NOT origin_count EQUAL 1)
                rf_bootstrap_fail("RF1231" "bootstrap CMake must have exactly one authority origin")
            endif()
            string(JSON cmake_origin GET "${artifact_json}" artifacts ${artifact_index} origins 0)
            rf_require_json_members(artifact_json "bootstrap CMake signature" "required,scheme,expectedIdentity,verificationArtifactIds" artifacts ${artifact_index} signature)
            rf_require_json_members(artifact_json "bootstrap CMake archive" "format,root,manifestReference" artifacts ${artifact_index} archive)
            foreach(field IN ITEMS format root manifestReference)
                string(JSON cmake_archive_${field} GET "${artifact_json}" artifacts ${artifact_index} archive ${field})
            endforeach()
            string(JSON signature_required GET "${artifact_json}" artifacts ${artifact_index} signature required)
            string(JSON signature_scheme GET "${artifact_json}" artifacts ${artifact_index} signature scheme)
            if(NOT signature_required OR NOT signature_scheme STREQUAL "gpg" OR NOT cmake_role STREQUAL "build_tool")
                rf_bootstrap_fail("RF1232" "bootstrap CMake signature/role policy is invalid")
            endif()
        endif()
    endforeach()
    if(NOT artifact_found)
        rf_bootstrap_fail("RF1233" "bootstrap CMake artifact is missing for ${host_id}")
    endif()

    foreach(variable IN ITEMS minimum_cmake transport_absolutePath transport_version transport_byteSize transport_binarySha256
                              transport_packageIdentity cmake_version cmake_byteSize cmake_sha256 cmake_origin
                              cmake_archive_format cmake_archive_root cmake_archive_manifestReference)
        set(RF_${variable} "${${variable}}" PARENT_SCOPE)
    endforeach()
endfunction()

function(rf_load_artifact repository_root artifact_id output_prefix)
    rf_read_bounded_json("${repository_root}/third_party/artifacts.lock.json" artifact_json)
    string(JSON artifact_count LENGTH "${artifact_json}" artifacts)
    set(found FALSE)
    math(EXPR artifact_last "${artifact_count} - 1")
    foreach(artifact_index RANGE 0 ${artifact_last})
        string(JSON candidate_id GET "${artifact_json}" artifacts ${artifact_index} id)
        if(candidate_id STREQUAL artifact_id)
            if(found)
                rf_bootstrap_fail("RF1235" "duplicate artifact id in bootstrap authority")
            endif()
            set(found TRUE)
            foreach(field IN ITEMS version byteSize sha256 role catalogId)
                string(JSON value GET "${artifact_json}" artifacts ${artifact_index} ${field})
                set(${output_prefix}_${field} "${value}" PARENT_SCOPE)
            endforeach()
            string(JSON origin_count LENGTH "${artifact_json}" artifacts ${artifact_index} origins)
            if(NOT origin_count EQUAL 1)
                rf_bootstrap_fail("RF1236" "bootstrap verifier artifact must have one origin")
            endif()
            string(JSON value GET "${artifact_json}" artifacts ${artifact_index} origins 0)
            set(${output_prefix}_origin "${value}" PARENT_SCOPE)
            foreach(field IN ITEMS format manifestReference)
                string(JSON value GET "${artifact_json}" artifacts ${artifact_index} archive ${field})
                set(${output_prefix}_archive_${field} "${value}" PARENT_SCOPE)
            endforeach()
            set(${output_prefix}_archive_rootless_entry_count "" PARENT_SCOPE)
            set(${output_prefix}_archive_rootless_top_directories "" PARENT_SCOPE)
            set(${output_prefix}_archive_rootless_top_files "" PARENT_SCOPE)
            string(JSON value ERROR_VARIABLE root_error GET "${artifact_json}" artifacts ${artifact_index} archive root)
            if(NOT root_error)
                set(${output_prefix}_archive_root "${value}" PARENT_SCOPE)
            else()
                string(JSON root_count ERROR_VARIABLE roots_error LENGTH "${artifact_json}" artifacts ${artifact_index} archive roots)
                if(NOT roots_error)
                    if(root_count LESS 2)
                        rf_bootstrap_fail("RF1288" "artifact archive root set is not closed")
                    endif()
                    set(root_values "")
                    math(EXPR root_last "${root_count} - 1")
                    foreach(root_index RANGE 0 ${root_last})
                        string(JSON value GET "${artifact_json}" artifacts ${artifact_index} archive roots ${root_index})
                        list(APPEND root_values "${value}")
                    endforeach()
                    set(${output_prefix}_archive_root "${root_values}" PARENT_SCOPE)
                else()
                    string(JSON rootless_type ERROR_VARIABLE rootless_error
                        TYPE "${artifact_json}" artifacts ${artifact_index} archive rootless)
                    if(rootless_error OR NOT rootless_type STREQUAL "OBJECT")
                        rf_bootstrap_fail("RF1288" "artifact archive declares neither root, roots, nor rootless")
                    endif()
                    foreach(pair IN ITEMS "entryCount|entry_count" "topLevelDirectories|top_directories" "topLevelFiles|top_files")
                        string(REPLACE "|" ";" pair_fields "${pair}")
                        list(GET pair_fields 0 member)
                        list(GET pair_fields 1 suffix)
                        string(JSON value ERROR_VARIABLE member_error
                            GET "${artifact_json}" artifacts ${artifact_index} archive rootless ${member})
                        if(member_error OR NOT value MATCHES "^[0-9]+$")
                            rf_bootstrap_fail("RF1313" "rootless archive contract is incomplete")
                        endif()
                        set(${output_prefix}_archive_rootless_${suffix} "${value}" PARENT_SCOPE)
                    endforeach()
                    set(${output_prefix}_archive_root "" PARENT_SCOPE)
                endif()
            endif()
            string(JSON value GET "${artifact_json}" artifacts ${artifact_index} signature scheme)
            set(${output_prefix}_signature_scheme "${value}" PARENT_SCOPE)
            string(JSON value GET "${artifact_json}" artifacts ${artifact_index} signature expectedIdentity)
            set(${output_prefix}_expected_identity "${value}" PARENT_SCOPE)
        endif()
    endforeach()
    if(NOT found)
        rf_bootstrap_fail("RF1237" "required bootstrap verifier artifact is missing")
    endif()
endfunction()

function(rf_load_required_file repository_root artifact_id required_path output_prefix)
    rf_read_bounded_json("${repository_root}/third_party/artifacts.lock.json" artifact_json)
    string(JSON artifact_count LENGTH "${artifact_json}" artifacts)
    set(found FALSE)
    math(EXPR artifact_last "${artifact_count} - 1")
    foreach(artifact_index RANGE 0 ${artifact_last})
        string(JSON candidate_id GET "${artifact_json}" artifacts ${artifact_index} id)
        if(candidate_id STREQUAL artifact_id)
            string(JSON required_count ERROR_VARIABLE required_error LENGTH "${artifact_json}" artifacts ${artifact_index} archive requiredFiles)
            if(required_error OR required_count LESS 1)
                rf_bootstrap_fail("RF1238" "artifact has no required-file authority")
            endif()
            math(EXPR required_last "${required_count} - 1")
            foreach(required_index RANGE 0 ${required_last})
                string(JSON candidate_path GET "${artifact_json}" artifacts ${artifact_index} archive requiredFiles ${required_index} path)
                if(candidate_path STREQUAL required_path)
                    if(found)
                        rf_bootstrap_fail("RF1239" "duplicate required-file authority")
                    endif()
                    set(found TRUE)
                    foreach(field IN ITEMS byteSize sha256)
                        string(JSON value GET "${artifact_json}" artifacts ${artifact_index} archive requiredFiles ${required_index} ${field})
                        set(${output_prefix}_${field} "${value}" PARENT_SCOPE)
                    endforeach()
                endif()
            endforeach()
        endif()
    endforeach()
    if(NOT found)
        rf_bootstrap_fail("RF1279" "required inner file is not locked")
    endif()
endfunction()
