include_guard(GLOBAL)

function(rf_quarantine_artifact repository_root bootstrap_root quarantine_root curl_executable artifact_id output_prefix)
    rf_load_artifact("${repository_root}" "${artifact_id}" artifact)
    set(path "${quarantine_root}/artifact-${artifact_sha256}")
    if(NOT EXISTS "${path}")
        set(prestaged "${bootstrap_root}/prestaged/artifact-${artifact_sha256}")
        if(EXISTS "${prestaged}")
            file(COPY_FILE "${prestaged}" "${path}" ONLY_IF_DIFFERENT)
        else()
            rf_download_manually_redirected(
                "${curl_executable}" "${artifact_origin}" "${path}" "${artifact_byteSize}"
                redirect_hops transport_hosts
            )
        endif()
    endif()
    rf_verify_file_identity("${path}" "${artifact_byteSize}" "${artifact_sha256}" "quarantined ${artifact_id}")
    foreach(field IN ITEMS path version byteSize sha256 origin archive_root archive_format signature_scheme expected_identity)
        if(field STREQUAL "path")
            set(value "${path}")
        else()
            set(value "${artifact_${field}}")
        endif()
        set(${output_prefix}_${field} "${value}" PARENT_SCOPE)
    endforeach()
endfunction()

function(rf_assert_owned_tree tree)
    file(REAL_PATH "${tree}" tree_real)
    file(GLOB_RECURSE entries LIST_DIRECTORIES TRUE "${tree}/*")
    foreach(entry IN LISTS entries)
        file(REAL_PATH "${entry}" entry_real)
        cmake_path(IS_PREFIX tree_real "${entry_real}" NORMALIZE owned)
        if(NOT owned)
            rf_bootstrap_fail("RF1280" "extracted verifier content escapes quarantine")
        endif()
    endforeach()
endfunction()

function(rf_extract_seven_zip sfx_path destination output_executable)
    if(NOT EXISTS "${destination}")
        set(incoming "${destination}.incoming")
        file(REMOVE_RECURSE "${incoming}")
        file(MAKE_DIRECTORY "${incoming}")
        file(ARCHIVE_EXTRACT INPUT "${sfx_path}" DESTINATION "${incoming}")
        rf_assert_owned_tree("${incoming}")
        foreach(required IN ITEMS 7z.exe 7z.dll License.txt)
            if(NOT EXISTS "${incoming}/${required}")
                file(REMOVE_RECURSE "${incoming}")
                rf_bootstrap_fail("RF1281" "7-Zip bootstrap extraction is incomplete")
            endif()
        endforeach()
        file(RENAME "${incoming}" "${destination}" RESULT rename_result)
        if(NOT rename_result STREQUAL "0")
            file(REMOVE_RECURSE "${incoming}")
            rf_bootstrap_fail("RF1282" "cannot publish 7-Zip quarantine tree")
        endif()
    endif()
    set(${output_executable} "${destination}/7z.exe" PARENT_SCOPE)
endfunction()

function(rf_extract_gnupg_windows seven_zip installer destination output_gpg output_gpgv output_gpgconf output_keyring)
    if(NOT EXISTS "${destination}")
        set(incoming "${destination}.incoming")
        file(REMOVE_RECURSE "${incoming}")
        file(MAKE_DIRECTORY "${incoming}")
        execute_process(
            COMMAND "${seven_zip}" x -y -aoa -snl- -snh- "-o${incoming}" "${installer}"
            RESULT_VARIABLE extract_result
            OUTPUT_VARIABLE extract_output
            ERROR_VARIABLE extract_error
            TIMEOUT 120
        )
        string(LENGTH "${extract_output}${extract_error}" output_bytes)
        if(NOT extract_result EQUAL 0 OR output_bytes GREATER 1048576)
            file(REMOVE_RECURSE "${incoming}")
            rf_bootstrap_fail("RF1283" "registry-free GnuPG extraction failed")
        endif()
        rf_assert_owned_tree("${incoming}")
        foreach(required IN ITEMS bin/gpg.exe bin/gpgv.exe bin/gpgconf.exe share/gnupg/distsigkey.gpg)
            if(NOT EXISTS "${incoming}/${required}")
                file(REMOVE_RECURSE "${incoming}")
                rf_bootstrap_fail("RF1284" "GnuPG quarantine tree is incomplete")
            endif()
        endforeach()
        file(RENAME "${incoming}" "${destination}" RESULT rename_result)
        if(NOT rename_result STREQUAL "0")
            file(REMOVE_RECURSE "${incoming}")
            rf_bootstrap_fail("RF1285" "cannot publish GnuPG quarantine tree")
        endif()
    endif()
    set(${output_gpg} "${destination}/bin/gpg.exe" PARENT_SCOPE)
    set(${output_gpgv} "${destination}/bin/gpgv.exe" PARENT_SCOPE)
    set(${output_gpgconf} "${destination}/bin/gpgconf.exe" PARENT_SCOPE)
    set(${output_keyring} "${destination}/share/gnupg/distsigkey.gpg" PARENT_SCOPE)
endfunction()

function(rf_verify_gnupg_windows gpg gpgv keyring signature installer quarantine_root)
    set(home "${quarantine_root}/gnupg-self-home")
    file(MAKE_DIRECTORY "${home}")
    execute_process(
        COMMAND "${gpgv}" --version
        RESULT_VARIABLE version_result OUTPUT_VARIABLE version_output ERROR_VARIABLE version_error TIMEOUT 10
    )
    if(NOT version_result EQUAL 0 OR NOT version_output MATCHES "^gpgv \\(GnuPG\\) 2\\.5\\.21")
        rf_bootstrap_fail("RF1286" "GnuPG verifier version mismatch")
    endif()
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env "GNUPGHOME=${home}"
            "${gpgv}" --homedir "${home}" --status-fd=1 --keyring "${keyring}" "${signature}" "${installer}"
        RESULT_VARIABLE verify_result OUTPUT_VARIABLE verify_output ERROR_VARIABLE verify_error TIMEOUT 30
    )
    string(LENGTH "${verify_output}${verify_error}" output_bytes)
    if(NOT verify_result EQUAL 0 OR output_bytes GREATER 262144 OR
       NOT verify_output MATCHES "VALIDSIG 6DAA6E64A76D2840571B4902528897B826403ADA")
        rf_bootstrap_fail("RF1287" "GnuPG bootstrap self-signature verification failed")
    endif()
endfunction()

function(rf_extract_flat_archive archive destination required_path expected_bytes expected_sha256 output_path)
    if(NOT EXISTS "${destination}")
        set(incoming "${destination}.incoming")
        file(REMOVE_RECURSE "${incoming}")
        file(MAKE_DIRECTORY "${incoming}")
        file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${incoming}")
        rf_assert_owned_tree("${incoming}")
        rf_verify_file_identity("${incoming}/${required_path}" "${expected_bytes}" "${expected_sha256}" "required extracted verifier")
        file(RENAME "${incoming}" "${destination}" RESULT rename_result)
        if(NOT rename_result STREQUAL "0")
            file(REMOVE_RECURSE "${incoming}")
            rf_bootstrap_fail("RF1295" "cannot publish flat verifier quarantine tree")
        endif()
    endif()
    rf_verify_file_identity("${destination}/${required_path}" "${expected_bytes}" "${expected_sha256}" "required extracted verifier")
    file(CHMOD "${destination}/${required_path}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    set(${output_path} "${destination}/${required_path}" PARENT_SCOPE)
endfunction()

function(rf_extract_debian_payload package destination required_path expected_bytes expected_sha256 output_path)
    if(NOT EXISTS "${destination}")
        set(package_incoming "${destination}.package.incoming")
        set(payload_incoming "${destination}.incoming")
        file(REMOVE_RECURSE "${package_incoming}" "${payload_incoming}")
        file(MAKE_DIRECTORY "${package_incoming}" "${payload_incoming}")
        file(ARCHIVE_EXTRACT INPUT "${package}" DESTINATION "${package_incoming}")
        rf_assert_owned_tree("${package_incoming}")
        if(NOT EXISTS "${package_incoming}/data.tar.zst")
            rf_bootstrap_fail("RF1296" "locked Debian package lacks data.tar.zst")
        endif()
        file(ARCHIVE_EXTRACT INPUT "${package_incoming}/data.tar.zst" DESTINATION "${payload_incoming}")
        rf_assert_owned_tree("${payload_incoming}")
        rf_verify_file_identity("${payload_incoming}/${required_path}" "${expected_bytes}" "${expected_sha256}" "required Debian payload file")
        file(RENAME "${payload_incoming}" "${destination}" RESULT rename_result)
        file(REMOVE_RECURSE "${package_incoming}")
        if(NOT rename_result STREQUAL "0")
            file(REMOVE_RECURSE "${payload_incoming}")
            rf_bootstrap_fail("RF1297" "cannot publish Debian verifier quarantine tree")
        endif()
    endif()
    rf_verify_file_identity("${destination}/${required_path}" "${expected_bytes}" "${expected_sha256}" "required Debian payload file")
    set(${output_path} "${destination}/${required_path}" PARENT_SCOPE)
endfunction()

function(rf_require_debian_package_record packages_text package version filename bytes sha256)
    set(marker "Package: ${package}\n")
    string(FIND "${packages_text}" "${marker}" first_offset)
    if(first_offset EQUAL -1)
        rf_bootstrap_fail("RF1298" "signed Packages index lacks a bootstrap package")
    endif()
    string(SUBSTRING "${packages_text}" ${first_offset} -1 tail)
    string(FIND "${tail}" "\n\n" block_end)
    if(block_end EQUAL -1)
        rf_bootstrap_fail("RF1299" "signed Packages index has a malformed package paragraph")
    endif()
    string(SUBSTRING "${tail}" 0 ${block_end} block)
    math(EXPR after_marker "${first_offset} + 1")
    string(SUBSTRING "${packages_text}" ${after_marker} -1 remaining)
    string(FIND "${remaining}" "${marker}" duplicate_offset)
    if(NOT duplicate_offset EQUAL -1)
        rf_bootstrap_fail("RF1300" "signed Packages index contains a duplicate bootstrap package")
    endif()
    foreach(field IN ITEMS "Version: ${version}" "Filename: ${filename}" "Size: ${bytes}" "SHA256: ${sha256}")
        string(FIND "\n${block}\n" "\n${field}\n" field_offset)
        if(field_offset EQUAL -1)
            rf_bootstrap_fail("RF1301" "signed Packages index disagrees with a locked package identity")
        endif()
    endforeach()
endfunction()

function(rf_verify_gnupg_linux repository_root bootstrap_root quarantine_root curl_executable output_gpg output_gpgv output_gpgconf)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "tool.archive_extractor.linux_x86_64" seven_zip)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "tool.gnupg.linux_x86_64" gpgv_pkg)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "tool.gnupg.linux_x86_64_full" gpg_pkg)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "tool.gnupg.linux_x86_64_config" gpgconf_pkg)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "authority.ubuntu_archive_keyring.linux_all" key_pkg)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "host.ubuntu.noble_inrelease" inrelease)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "host.ubuntu.noble_packages" packages)

    rf_load_required_file("${repository_root}" "tool.archive_extractor.linux_x86_64" "7zz" seven_zip_inner)
    rf_load_required_file("${repository_root}" "tool.gnupg.linux_x86_64" "usr/bin/gpgv" gpgv_inner)
    rf_load_required_file("${repository_root}" "tool.gnupg.linux_x86_64_full" "usr/bin/gpg" gpg_inner)
    rf_load_required_file("${repository_root}" "tool.gnupg.linux_x86_64_config" "usr/bin/gpgconf" gpgconf_inner)
    rf_load_required_file("${repository_root}" "authority.ubuntu_archive_keyring.linux_all" "usr/share/keyrings/ubuntu-archive-keyring.gpg" key_inner)

    rf_extract_flat_archive("${seven_zip_path}" "${quarantine_root}/seven-zip-${seven_zip_sha256}" "7zz" "${seven_zip_inner_byteSize}" "${seven_zip_inner_sha256}" seven_zip_executable)
    rf_extract_debian_payload("${gpgv_pkg_path}" "${quarantine_root}/gpgv-${gpgv_pkg_sha256}" "usr/bin/gpgv" "${gpgv_inner_byteSize}" "${gpgv_inner_sha256}" gpgv_executable)
    rf_extract_debian_payload("${gpg_pkg_path}" "${quarantine_root}/gpg-${gpg_pkg_sha256}" "usr/bin/gpg" "${gpg_inner_byteSize}" "${gpg_inner_sha256}" gpg_executable)
    rf_extract_debian_payload("${gpgconf_pkg_path}" "${quarantine_root}/gpgconf-${gpgconf_pkg_sha256}" "usr/bin/gpgconf" "${gpgconf_inner_byteSize}" "${gpgconf_inner_sha256}" gpgconf_executable)
    rf_extract_debian_payload("${key_pkg_path}" "${quarantine_root}/ubuntu-keyring-${key_pkg_sha256}" "usr/share/keyrings/ubuntu-archive-keyring.gpg" "${key_inner_byteSize}" "${key_inner_sha256}" archive_keyring)
    file(CHMOD "${gpgv_executable}" "${gpg_executable}" "${gpgconf_executable}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)

    set(home "${quarantine_root}/ubuntu-package-signing-home")
    file(MAKE_DIRECTORY "${home}")
    execute_process(
        COMMAND "${gpgv_executable}" --homedir "${home}" --status-fd=1 --keyring "${archive_keyring}" "${inrelease_path}"
        RESULT_VARIABLE verify_result OUTPUT_VARIABLE verify_output ERROR_VARIABLE verify_error TIMEOUT 30
    )
    if(NOT verify_result EQUAL 0 OR NOT verify_output MATCHES "VALIDSIG F6ECB3762474EDA9D21B7022871920D1991BC93C")
        rf_bootstrap_fail("RF1302" "Canonical noble InRelease verification failed")
    endif()

    file(READ "${inrelease_path}" inrelease_text LIMIT 262144)
    string(REGEX MATCHALL "\n ${packages_sha256}[ \t]+${packages_byteSize} main/binary-amd64/Packages\\.gz\n" package_index_matches "${inrelease_text}")
    list(LENGTH package_index_matches package_index_count)
    if(NOT package_index_count EQUAL 1)
        rf_bootstrap_fail("RF1303" "signed InRelease does not select the exact Packages index")
    endif()

    set(packages_tree "${quarantine_root}/packages-${packages_sha256}")
    if(NOT EXISTS "${packages_tree}/Packages")
        set(packages_incoming "${packages_tree}.incoming")
        file(REMOVE_RECURSE "${packages_incoming}")
        file(MAKE_DIRECTORY "${packages_incoming}")
        execute_process(
            COMMAND "${seven_zip_executable}" x -so "${packages_path}"
            RESULT_VARIABLE extract_result OUTPUT_FILE "${packages_incoming}/Packages" ERROR_VARIABLE extract_error TIMEOUT 60
        )
        if(NOT extract_result EQUAL 0 OR NOT EXISTS "${packages_incoming}/Packages")
            file(REMOVE_RECURSE "${packages_incoming}")
            rf_bootstrap_fail("RF1304" "cannot decompress the signed Packages index")
        endif()
        file(RENAME "${packages_incoming}" "${packages_tree}" RESULT rename_result)
        if(NOT rename_result STREQUAL "0")
            file(REMOVE_RECURSE "${packages_incoming}")
            rf_bootstrap_fail("RF1305" "cannot publish decompressed Packages quarantine tree")
        endif()
    endif()
    file(SIZE "${packages_tree}/Packages" packages_uncompressed_bytes)
    if(packages_uncompressed_bytes GREATER 67108864)
        rf_bootstrap_fail("RF1306" "decompressed Packages index exceeds 64 MiB")
    endif()
    file(READ "${packages_tree}/Packages" packages_text LIMIT 67108865)
    foreach(prefix IN ITEMS gpgv_pkg gpg_pkg gpgconf_pkg key_pkg)
        string(REGEX REPLACE "^https://archive\\.ubuntu\\.com/ubuntu/" "" filename "${${prefix}_origin}")
        if(prefix STREQUAL "gpgv_pkg")
            set(package_name gpgv)
        elseif(prefix STREQUAL "gpg_pkg")
            set(package_name gpg)
        elseif(prefix STREQUAL "gpgconf_pkg")
            set(package_name gpgconf)
        else()
            set(package_name ubuntu-keyring)
        endif()
        rf_require_debian_package_record("${packages_text}" "${package_name}" "${${prefix}_version}" "${filename}" "${${prefix}_byteSize}" "${${prefix}_sha256}")
    endforeach()

    execute_process(COMMAND "${gpgv_executable}" --version RESULT_VARIABLE gpgv_version_result OUTPUT_VARIABLE gpgv_version_output ERROR_QUIET TIMEOUT 10)
    execute_process(COMMAND "${gpg_executable}" --version RESULT_VARIABLE gpg_version_result OUTPUT_VARIABLE gpg_version_output ERROR_QUIET TIMEOUT 10)
    execute_process(COMMAND "${gpgconf_executable}" --version RESULT_VARIABLE gpgconf_version_result OUTPUT_VARIABLE gpgconf_version_output ERROR_QUIET TIMEOUT 10)
    if(NOT gpgv_version_result EQUAL 0 OR NOT gpg_version_result EQUAL 0 OR NOT gpgconf_version_result EQUAL 0 OR
       NOT gpgv_version_output MATCHES "^gpgv \\(GnuPG\\) 2\\.4\\.4" OR NOT gpg_version_output MATCHES "^gpg \\(GnuPG\\) 2\\.4\\.4" OR
       NOT gpgconf_version_output MATCHES "^gpgconf \\(GnuPG\\) 2\\.4\\.4")
        rf_bootstrap_fail("RF1307" "Linux GnuPG verifier version mismatch")
    endif()

    set(${output_gpg} "${gpg_executable}" PARENT_SCOPE)
    set(${output_gpgv} "${gpgv_executable}" PARENT_SCOPE)
    set(${output_gpgconf} "${gpgconf_executable}" PARENT_SCOPE)
    set(RF_LINUX_SEVEN_ZIP_TREE "${quarantine_root}/seven-zip-${seven_zip_sha256}" PARENT_SCOPE)
    set(RF_LINUX_ARCHIVE_KEYRING "${archive_keyring}" PARENT_SCOPE)
    set(RF_LINUX_VERIFIER_ARTIFACT_PATHS "${seven_zip_path};${gpgv_pkg_path};${gpg_pkg_path};${gpgconf_pkg_path};${key_pkg_path};${inrelease_path};${packages_path}" PARENT_SCOPE)
    set(RF_LINUX_VERIFIER_ARTIFACT_IDS "tool.archive_extractor.linux_x86_64;tool.gnupg.linux_x86_64;tool.gnupg.linux_x86_64_full;tool.gnupg.linux_x86_64_config;authority.ubuntu_archive_keyring.linux_all;host.ubuntu.noble_inrelease;host.ubuntu.noble_packages" PARENT_SCOPE)
endfunction()

function(rf_verify_cmake_release repository_root bootstrap_root quarantine_root curl_executable gpg gpgv gpgconf cmake_origin cmake_sha256)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "authority.cmake_release_key.data" key)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "tool.cmake.checksums" sums)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "tool.cmake.checksums_signature" sums_sig)

    set(home "${quarantine_root}/cmake-signing-home")
    file(REMOVE_RECURSE "${home}")
    file(MAKE_DIRECTORY "${home}")
    execute_process(
        COMMAND "${gpg}" --no-options --homedir "${home}" --batch --with-colons --show-keys "${key_path}"
        RESULT_VARIABLE show_result OUTPUT_VARIABLE show_output ERROR_VARIABLE show_error TIMEOUT 20
    )
    if(NOT show_result EQUAL 0 OR NOT show_output MATCHES "fpr:::::::::C6C265324BBEBDC350B513D02D2CEF1034921684:")
        rf_bootstrap_fail("RF1288" "CMake release key fingerprint mismatch")
    endif()
    execute_process(
        COMMAND "${gpg}" --no-options --homedir "${home}" --batch --import "${key_path}"
        RESULT_VARIABLE import_result OUTPUT_QUIET ERROR_QUIET TIMEOUT 20
    )
    if(NOT import_result EQUAL 0 OR NOT EXISTS "${home}/pubring.kbx")
        rf_bootstrap_fail("RF1289" "cannot construct isolated CMake release keyring")
    endif()
    execute_process(
        COMMAND "${gpgv}" --homedir "${home}" --status-fd=1 --keyring "${home}/pubring.kbx" "${sums_sig_path}" "${sums_path}"
        RESULT_VARIABLE verify_result OUTPUT_VARIABLE verify_output ERROR_VARIABLE verify_error TIMEOUT 30
    )
    if(NOT verify_result EQUAL 0 OR NOT verify_output MATCHES "VALIDSIG C6C265324BBEBDC350B513D02D2CEF1034921684")
        rf_bootstrap_fail("RF1290" "CMake checksum OpenPGP signature verification failed")
    endif()
    rf_shutdown_gnupg_home("${gpgconf}" "${home}")

    string(REGEX REPLACE "^.*/" "" archive_name "${cmake_origin}")
    file(READ "${sums_path}" checksum_text LIMIT 4096)
    string(REPLACE "\r" "" checksum_text "${checksum_text}")
    string(REPLACE "\n" ";" checksum_lines "${checksum_text}")
    set(match_count 0)
    foreach(line IN LISTS checksum_lines)
        if(line MATCHES "^${cmake_sha256}[ \t]+\\*?${archive_name}$")
            math(EXPR match_count "${match_count} + 1")
        endif()
    endforeach()
    if(NOT match_count EQUAL 1)
        rf_bootstrap_fail("RF1291" "selected CMake digest is not unique in the signed checksum manifest")
    endif()

    set(RF_CMAKE_SIDECAR_PATHS "${key_path};${sums_path};${sums_sig_path}" PARENT_SCOPE)
    set(RF_CMAKE_SIDECAR_IDS "authority.cmake_release_key.data;tool.cmake.checksums;tool.cmake.checksums_signature" PARENT_SCOPE)
endfunction()

function(rf_verify_cosign repository_root bootstrap_root quarantine_root curl_executable host_id)
    string(REPLACE "-" "_" host_token "${host_id}")
    set(binary_id "tool.cosign.${host_token}")
    set(bundle_id "tool.cosign.${host_token}_bundle")
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "${binary_id}" cosign)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "${bundle_id}" bundle)
    rf_quarantine_artifact("${repository_root}" "${bootstrap_root}" "${quarantine_root}" "${curl_executable}" "authority.sigstore_trusted_root.data" trusted_root)
    if(host_id STREQUAL "linux-x86_64")
        file(CHMOD "${cosign_path}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    endif()
    execute_process(
        COMMAND "${cosign_path}" version
        RESULT_VARIABLE version_result OUTPUT_VARIABLE version_output ERROR_VARIABLE version_error TIMEOUT 15
    )
    if(NOT version_result EQUAL 0 OR NOT "${version_output}${version_error}" MATCHES "v3\\.0\\.6")
        rf_bootstrap_fail("RF1292" "Cosign verifier version mismatch")
    endif()
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env --unset=HTTP_PROXY --unset=HTTPS_PROXY --unset=ALL_PROXY
            "${cosign_path}" verify-blob --bundle "${bundle_path}" --trusted-root "${trusted_root_path}"
            --certificate-identity "keyless@projectsigstore.iam.gserviceaccount.com"
            --certificate-oidc-issuer "https://accounts.google.com" "${cosign_path}"
        RESULT_VARIABLE verify_result OUTPUT_VARIABLE verify_output ERROR_VARIABLE verify_error TIMEOUT 60
    )
    string(LENGTH "${verify_output}${verify_error}" output_bytes)
    if(NOT verify_result EQUAL 0 OR output_bytes GREATER 524288)
        rf_bootstrap_fail("RF1293" "Cosign bootstrap self-provenance verification failed")
    endif()
    set(RF_COSIGN_PATH "${cosign_path}" PARENT_SCOPE)
    set(RF_COSIGN_ARTIFACT_PATHS "${cosign_path};${bundle_path};${trusted_root_path}" PARENT_SCOPE)
    set(RF_COSIGN_ARTIFACT_IDS "${binary_id};${bundle_id};authority.sigstore_trusted_root.data" PARENT_SCOPE)
endfunction()

function(rf_publish_verified_file cache_root source sha256 expected_bytes)
    string(SUBSTRING "${sha256}" 0 2 prefix)
    set(directory "${cache_root}/objects/${prefix}")
    set(destination "${directory}/${sha256}")
    file(MAKE_DIRECTORY "${directory}")
    if(EXISTS "${destination}")
        rf_verify_file_identity("${destination}" "${expected_bytes}" "${sha256}" "existing cache object")
        return()
    endif()
    set(incoming "${destination}.incoming")
    file(REMOVE "${incoming}")
    file(COPY_FILE "${source}" "${incoming}")
    rf_verify_file_identity("${incoming}" "${expected_bytes}" "${sha256}" "incoming cache object")
    file(RENAME "${incoming}" "${destination}" RESULT rename_result)
    if(NOT rename_result STREQUAL "0")
        file(REMOVE "${incoming}")
        rf_bootstrap_fail("RF1294" "cannot atomically publish verified cache object")
    endif()
endfunction()

function(rf_publish_locked_artifact repository_root cache_root artifact_id source)
    rf_load_artifact("${repository_root}" "${artifact_id}" locked)
    rf_verify_file_identity("${source}" "${locked_byteSize}" "${locked_sha256}" "verified ${artifact_id}")
    rf_publish_verified_file("${cache_root}" "${source}" "${locked_sha256}" "${locked_byteSize}")
endfunction()

function(rf_read_prepared_marker tree output_variable)
    set(marker "${tree}/.rf-prepared.json")
    if(IS_SYMLINK "${marker}" OR NOT EXISTS "${marker}" OR IS_DIRECTORY "${marker}")
        rf_bootstrap_fail("RF1308" "prepared tree lacks a readable identity marker")
    endif()
    file(SIZE "${marker}" marker_bytes)
    if(marker_bytes GREATER 4096)
        rf_bootstrap_fail("RF1308" "prepared identity marker exceeds bounds")
    endif()
    file(READ "${marker}" marker_text LIMIT 4097)
    set(${output_variable} "${marker_text}" PARENT_SCOPE)
endfunction()

# Bounded fail-closed recovery for stale prepared-tree rollback state,
# accepted by the 2026-07-16 TASK-0001 owner amendment. Automatic action
# requires exact containment beneath the accepted prepared root, no
# link/reparse indirection, an exact marker match against the desired
# identity, and an unambiguous current/previous/incoming state. Every other
# state deletes nothing, chooses nothing, and stops with RF1308. An empty
# recovery root keeps the strict pre-amendment behavior.
function(rf_recover_prepared_rollback recovery_root destination marker_content)
    set(previous "${destination}.previous")
    if(NOT EXISTS "${previous}")
        return()
    endif()
    if(recovery_root STREQUAL "")
        rf_bootstrap_fail("RF1308" "stale prepared-tree rollback state exists")
    endif()
    if(EXISTS "${destination}.incoming")
        rf_bootstrap_fail("RF1308" "rollback recovery is ambiguous: incoming and previous both exist")
    endif()
    if(IS_SYMLINK "${previous}" OR NOT IS_DIRECTORY "${previous}")
        rf_bootstrap_fail("RF1308" "rollback state is not an owned directory")
    endif()
    file(REAL_PATH "${recovery_root}" recovery_root_real)
    foreach(tree IN ITEMS "${destination}" "${previous}")
        if(NOT EXISTS "${tree}")
            continue()
        endif()
        file(REAL_PATH "${tree}" tree_real)
        cmake_path(IS_PREFIX recovery_root_real "${tree_real}" NORMALIZE contained)
        if(NOT contained)
            rf_bootstrap_fail("RF1308" "rollback state escapes the accepted prepared root")
        endif()
    endforeach()
    if(EXISTS "${destination}")
        if(IS_SYMLINK "${destination}" OR NOT IS_DIRECTORY "${destination}")
            rf_bootstrap_fail("RF1308" "prepared destination is not an owned directory")
        endif()
        rf_read_prepared_marker("${destination}" destination_marker)
        if(NOT destination_marker STREQUAL marker_content)
            rf_bootstrap_fail("RF1308" "prepared destination identity does not match the desired identity")
        endif()
        rf_assert_owned_tree("${destination}")
        rf_assert_owned_tree("${previous}")
        file(REMOVE_RECURSE "${previous}")
        if(EXISTS "${previous}")
            rf_bootstrap_fail("RF1308" "cannot remove the verified-stale rollback tree")
        endif()
        return()
    endif()
    # The destination is missing: restore the single fully verified rollback
    # tree, then let the caller republish over it atomically.
    rf_read_prepared_marker("${previous}" previous_marker)
    if(NOT previous_marker STREQUAL marker_content)
        rf_bootstrap_fail("RF1308" "rollback tree identity does not match the desired identity")
    endif()
    rf_assert_owned_tree("${previous}")
    file(RENAME "${previous}" "${destination}" RESULT restore_result)
    if(NOT restore_result STREQUAL "0")
        rf_bootstrap_fail("RF1308" "cannot restore the verified rollback tree")
    endif()
endfunction()

function(rf_publish_prepared_tree source destination marker_content)
    # ARGV3 optionally names the accepted prepared root that authorizes the
    # bounded 2026-07-16 rollback recovery; omitted or empty keeps the strict
    # RF1308 behavior for publications outside out/prepared.
    set(recovery_root "")
    if(ARGC GREATER 3)
        set(recovery_root "${ARGV3}")
    endif()
    rf_recover_prepared_rollback("${recovery_root}" "${destination}" "${marker_content}")
    set(incoming "${destination}.incoming")
    set(previous "${destination}.previous")
    file(REMOVE_RECURSE "${incoming}")
    if(EXISTS "${previous}")
        rf_bootstrap_fail("RF1308" "stale prepared-tree rollback state exists")
    endif()
    file(MAKE_DIRECTORY "${incoming}")
    file(COPY "${source}/" DESTINATION "${incoming}")
    rf_assert_owned_tree("${incoming}")
    file(WRITE "${incoming}/.rf-prepared.json" "${marker_content}")
    if(EXISTS "${destination}")
        file(RENAME "${destination}" "${previous}" RESULT previous_result)
        if(NOT previous_result STREQUAL "0")
            file(REMOVE_RECURSE "${incoming}")
            rf_bootstrap_fail("RF1309" "cannot stage existing prepared tree for replacement")
        endif()
    endif()
    file(RENAME "${incoming}" "${destination}" RESULT rename_result)
    if(NOT rename_result STREQUAL "0")
        file(REMOVE_RECURSE "${incoming}")
        if(EXISTS "${previous}")
            file(RENAME "${previous}" "${destination}" RESULT rollback_result)
        endif()
        rf_bootstrap_fail("RF1312" "cannot atomically publish prepared tool tree")
    endif()
    file(REMOVE_RECURSE "${previous}")
    # file(REMOVE_RECURSE) is best-effort: a locked file leaves a partial,
    # marker-less rollback tree behind silently. Fail loudly instead; the
    # published destination stays valid and the next run's bounded recovery
    # removes the verified-stale leftover.
    if(EXISTS "${previous}")
        rf_bootstrap_fail("RF1308" "cannot remove the replaced rollback tree")
    endif()
endfunction()
